version: '3'

services:

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    restart: always
    ports:
      - "8065:8065"
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE=mmuser:mmuser_password@tcp(mysql:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mattermost
      MYSQL_USER: mmuser
      MYSQL_PASSWORD: mmuser_password
